# Generated by Django 4.1.4 on 2022-12-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_customer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='grade',
            field=models.IntegerField(verbose_name=range(1, 50)),
        ),
    ]
