# Generated by Django 4.1.4 on 2022-12-29 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_customer_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
